### ISSUE TITLE
popup에 관한 문제

### ISSUE THREAD

**Issue by JoMingyu** [JoMingyu/Whale-GitPainter#3]
cpick에 preview가 따로 있어서, 팝업을 열고 나서도 colorpicker를 열고닫을 수 있다는 이슈가 있습니다.
브라우저 상에서 팝업을 열었을 때 colorpicker 본문이 바로 나올 수 있도록 수정이 필요합니다.

**Comment by AshtonYoon** [comment]
해결 :) 👍
