### ISSUE TITLE
팝업 로직 작성(도와줘요 여환이형!)

### ISSUE THREAD

**Issue by JoMingyu** [JoMingyu/Whale-GitPainter#5]
1. 팝업 내부 자체적인 기능들 : 컬러 선택 시 RGB, HEX 바인딩과 반대 방향 바인딩(RGB나 HEX 입력 시 컬러가 선택되도록 하는 것)
2. 사용자 설정에 따라 보여지는 컬러 : colormanager.js의 함수와 변수를 이용하면 됩니다. loadColors 함수의 콜백 내부에서 originColors 배열에 접근하여 컬러 코드를 가져가면 됩니다.
3. 사용자의 설정 : colormanager.js의 saveColor 함수를 이용하면 됩니다. position으로 0~4 사이의 위치를 지정하고, colorCode로 #이 포함된 hex 형태의 컬러 코드를 보내면 됩니다.

**Comment by AshtonYoon** [comment]
로직 끝! 👍
